version: "3.9"

services:
  concrete_datasource_backend:
    build:
      context: .
    container_name: concrete_datasource_backend
    image: rochel05/concrete_datasource_backend
    restart: always
    ports:
      - "8003:8003"

  test:
    build:
      context: .
    image: rochel05/concrete_datasource_backend
    command: python manage.py test
    depends_on:
      - concrete_datasource_backend
